
 ALTER TABLE `admin_operator_log`
MODIFY COLUMN `log_type`  enum('BUYER_INGOT','SELLER_INGOT','SELLER_PLEDGE','AUDIT_SELLER','AUDIT_SELLER_FAIL','AUDIT_TASK','AUDIT_TASK_FAIL','CANCEL_TASK','CANCEL_SUB_TASK','BUYER_DEPOSIT','CHANGE_USER') CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL AFTER `admin_account`;

